apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bci-gpt-model-pvc
  namespace: bci-gpt-production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: fast-ssd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bci-gpt-data-pvc
  namespace: bci-gpt-production
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: shared-storage
