apiVersion: v1
kind: ServiceAccount
metadata:
  name: bci-gpt-service-account
  namespace: bci-gpt-production
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: bci-gpt-production
  name: bci-gpt-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bci-gpt-role-binding
  namespace: bci-gpt-production
subjects:
- kind: ServiceAccount
  name: bci-gpt-service-account
  namespace: bci-gpt-production
roleRef:
  kind: Role
  name: bci-gpt-role
  apiGroup: rbac.authorization.k8s.io
